openapi: 3.1.0
info:
  title: API Documentation for LKAPI
  description: API for accessing user profile information.
  version: 1.0.0
servers:
  - url: https://apilk.iqdata.net
    description: Main server for LKAPI
    variables:
      host:
        default: apilk.iqdata.net
paths:
  /index.php/lkapi.account:
    get:
      summary: Get account data
      description: Retrieve account information based on the given parameters.
      operationId: getAccount
      tags:
        - Account
      parameters:
        - name: filters[class_cd-e-9]
          in: query
          description: Filter for account class (automatically filled)
          required: false
          schema:
            type: string
            default: pers_account
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          schema:
            type: integer
            default: 20
        - name: totals[balance]
          in: query
          description: Total balance calculation
          required: false
          schema:
            type: string
            default: sum
        - name: totals[chg]
          in: query
          description: Total change calculation
          required: false
          schema:
            type: string
            default: sum
        - name: _debug
          in: query
          description: Enable debug mode
          required: false
          schema:
            type: integer
            default: 1
        - name: _tz
          in: query
          description: Timezone offset in minutes
          required: false
          schema:
            type: integer
            default: 120
        - name: _schema
          in: query
          description: Schema identifier for the request
          required: false
          schema:
            type: string
            default: lkapi
        - name: token
          in: header
          description: Token for user authentication (required)
          required: true
          schema:
            type: string
        - name: db
          in: header
          description: Database identifier (automatically filled)
          required: false
          schema:
            type: string
            default: imaqliq_abonent
        - name: _app
          in: header
          description: Application version identifier (automatically filled)
          required: false
          schema:
            type: string
            default: platex_lk_application;1.1.10
        - name: Origin
          in: header
          description: Origin of the request (automatically filled)
          required: false
          schema:
            type: string
            default: https://lk.iqdata.net
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      app:
                        type: string
                        examples:
                          - platex-rest-api
                      version:
                        type: string
                        examples:
                          - 1.1.21
                      server_date:
                        type: string
                        examples:
                          - "2025-03-26 06:11:12"
                      status:
                        type: integer
                        examples:
                          - 200
                      time_ms:
                        type: integer
                        examples:
                          - 91
                      token:
                        type: object
                        properties:
                          token:
                            type: string
                            examples:
                              - "2af785ec-8d00-4faa-88b1-d5800e7d3c6e"
                      method:
                        type: string
                        examples:
                          - GET
                      path:
                        type: array
                        items:
                          type: string
                          examples:
                            - lkapi.account
                      act:
                        type: string
                        examples:
                          - s
                      in:
                        type: object
                        properties:
                          filters:
                            type: object
                            properties:
                              class_cd-e-9:
                                type: string
                                examples:
                                  - pers_account
                          limit:
                            type: string
                            examples:
                              - "20"
                          totals:
                            type: object
                            properties:
                              balance:
                                type: string
                                examples:
                                  - sum
                              chg:
                                type: string
                                examples:
                                  - sum
                      sql_info:
                        type: string
                        examples:
                          - "5 queries, 0.075 sec"
                      ref_table:
                        type: string
                        examples:
                          - lkapi