openapi: 3.0.3
info:
  title: API Documentation for LKAPI
  description: API for accessing user profile information.
  version: 1.0.0
servers:
  - url: https://apilk.iqdata.net
    description: Main server for LKAPI
    variables:
      host:
        default: apilk.iqdata.net
paths:
  /index.php/lkapi.account:
    get:
      summary: Get account data
      description: Retrieve account information based on the given parameters.
      operationId: getAccount
      parameters:
        - name: filters[class_cd-e-9]
          in: query
          description: Filter for account class (automatically filled)
          required: false
          schema:
            type: string
            default: pers_account
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          schema:
            type: integer
            default: 20
        - name: totals[balance]
          in: query
          description: Total balance calculation
          required: false
          schema:
            type: string
            default: sum
        - name: totals[chg]
          in: query
          description: Total change calculation
          required: false
          schema:
            type: string
            default: sum
        - name: _debug
          in: query
          description: Enable debug mode
          required: false
          schema:
            type: integer
            default: 1
        - name: _tz
          in: query
          description: Timezone offset in minutes
          required: false
          schema:
            type: integer
            default: 120
        - name: _schema
          in: query
          description: Schema identifier for the request
          required: false
          schema:
            type: string
            default: lkapi
        - name: token
          in: header
          description: Token for user authentication (required)
          required: true
          schema:
            type: string
        - name: db
          in: header
          description: Database identifier (automatically filled)
          required: false
          schema:
            type: string
            default: imaqliq_abonent
        - name: _app
          in: header
          description: Application version identifier (automatically filled)
          required: false
          schema:
            type: string
            default: platex_lk_application;1.1.10
        - name: Origin
          in: header
          description: Origin of the request (automatically filled)
          required: false
          schema:
            type: string
            default: https://lk.iqdata.net
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    description: Account data
                    properties:
                      accountId:
                        type: integer
                        example: 123
                      balance:
                        type: number
                        format: float
                        example: 1000.50
                      changes:
                        type: number
                        format: float
                        example: 50.00
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
