openapi: 3.1.0
info:
  title: LKAPI Contract API
  description: API для получения информации о контрактах.
  version: "1.1.21"
servers:
  - url: https://apilk.iqdata.net/index.php
    description: Production Server
paths:
  /lkapi.contract:
    get:
      summary: Получить информацию о контрактах
      description: Возвращает список контрактов для указанного аккаунта.
      parameters:
        - name: _debug
          in: query
          required: false
          description: Флаг отладки (1 - включить, 0 - выключить)
          schema:
            type: integer
            examples: [1, 0]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешный ответ с данными о контрактах.
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      app:
                        type: string
                        examples: ["platex-rest-api"]
                      version:
                        type: string
                        examples: ["1.1.21"]
                      server_date:
                        type: string
                        format: date-time
                        examples: ["2025-03-25 08:49:33"]
                      status:
                        type: integer
                        examples: [200]
                      time_ms:
                        type: integer
                        examples: [30]
                      token:
                        type: object
                        properties:
                          token:
                            type: string
                            examples: ["2a06ddba-7aa5-4cd9-8bb9-2efc2c5b783d"]
                      method:
                        type: string
                        examples: ["GET"]
                      path:
                        type: array
                        items:
                          type: string
                        examples: [["lkapi.contract"]]
                      act:
                        type: string
                        examples: ["s"]
                      in:
                        type: array
                        items:
                          type: string
                        examples: [[]]
                      sql_info:
                        type: string
                        examples: ["1 queries, 0.013 sec"]
                  data:
                    type: array
                    items:
                      type: object
                      # Описание полей контракта (в зависимости от структуры данных)
        '401':
          description: Ошибка аутентификации (неверный токен).
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      app:
                        type: string
                        examples: ["platex-rest-api"]
                      version:
                        type: string
                        examples: ["1.1.21"]
                      server_date:
                        type: string
                        format: date-time
                        examples: ["2025-03-25 08:49:33"]
                      status:
                        type: integer
                        examples: [401]
                      time_ms:
                        type: integer
                        examples: [30]
                      token:
                        type: object
                        properties:
                          error:
                            type: string
                            examples: ["Bad access token"]
                      method:
                        type: string
                        examples: ["GET"]
                      path:
                        type: array
                        items:
                          type: string
                        examples: [["lkapi.contract"]]
                      act:
                        type: string
                        examples: ["s"]
                      in:
                        type: array
                        items:
                          type: string
                        examples: [[]]
                      sql_info:
                        type: string
                        examples: ["1 queries, 0.013 sec"]
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: integer
                          examples: [401]
                        code:
                          type: integer
                          examples: [401]
                        title:
                          type: string
                          examples: ["Access token not valid"]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
