openapi: 3.1.0
info:
  title: LKAPI Contract API
  description: API для получения информации о контрактах.
  version: "1.1.21"
servers:
  - url: https://apilk.iqdata.net
    description: Основной сервер для LKAPI
    variables:
      host:
        default: apilk.iqdata.net
paths:
  /index.php/lkapi.contract:
    get:
      summary: Получить информацию о контрактах
      description: Возвращает список контрактов для указанного аккаунта.
      operationId: getContracts
      parameters:
        - name: _debug
          in: query
          description: Флаг отладки (1 - включить, 0 - выключить)
          required: false
          schema:
            type: integer
            default: 0
        - name: token
          in: header
          description: Токен для аутентификации пользователя
          required: true
          schema:
            type: string
        - name: db
          in: header
          description: Идентификатор базы данных
          required: true
          schema:
            type: string
            example: imaqliq_abonent
        - name: _app
          in: header
          description: Идентификатор версии приложения
          required: true
          schema:
            type: string
            example: platex_lk_application;1.1.10
        - name: Origin
          in: header
          description: Происхождение запроса
          required: true
          schema:
            type: string
            example: https://lk.iqdata.net
      responses:
        '200':
          description: Успешный ответ с данными о контрактах.
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      app:
                        type: string
                        example: platex-rest-api
                      version:
                        type: string
                        example: 1.1.21
                      server_date:
                        type: string
                        format: date-time
                        example: "2025-03-25T08:49:33"
                      status:
                        type: integer
                        example: 200
                      time_ms:
                        type: integer
                        example: 30
                      token:
                        type: object
                        properties:
                          token:
                            type: string
                            example: 2a06ddba-7aa5-4cd9-8bb9-2efc2c5b783d
                      method:
                        type: string
                        example: GET
                      path:
                        type: array
                        items:
                          type: string
                        example: [lkapi.contract]
                      act:
                        type: string
                        example: s
                      in:
                        type: array
                        items:
                          type: string
                        example: []
                      sql_info:
                        type: string
                        example: "1 queries, 0.013 sec"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        account_dn:
                          type: string
                          example: "94d28d19-1e62-4a4f-b46e-9bbc4a059152"
                        account_id:
                          type: integer
                          example: 4
                        contract_no:
                          type: string
                          example: "Договор Тестовича"
                        created:
                          type: string
                          format: date-time
                          example: "2025-03-06T17:44:47.459296+02"
                        # Добавьте другие поля контракта по мере необходимости
        '401':
          description: Ошибка аутентификации (неверный токен).
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      app:
                        type: string
                        example: platex-rest-api
                      version:
                        type: string
                        example: 1.1.21
                      server_date:
                        type: string
                        format: date-time
                        example: "2025-03-25T08:49:33"
                      status:
                        type: integer
                        example: 401
                      time_ms:
                        type: integer
                        example: 30
                      token:
                        type: object
                        properties:
                          error:
                            type: string
                            example: "Bad access token"
                      method:
                        type: string
                        example: GET
                      path:
                        type: array
                        items:
                          type: string
                        example: [lkapi.contract]
                      act:
