openapi: 3.1.0
info:
  title: LKAPI Current Service API
  description: API для получения текущей информации о сервисах.
  version: "1.1.21"
servers:
  - url: https://apilk.iqdata.net/index.php
    description: Production Server
paths:
  /lkapi.current_service:
    get:
      summary: Получить текущую информацию о сервисах
      description: Возвращает список текущих услуг для указанного аккаунта.
      parameters:
        - name: _debug
          in: query
          required: false
          description: Флаг отладки (1 - включить, 0 - выключить)
          schema:
            type: integer
            examples: [1, 0]
        - name: _tz
          in: query
          required: false
          description: Таймзона в минутах (например, 120 для GMT+2)
          schema:
            type: integer
            examples: [120]
        - name: _schema
          in: query
          required: false
          description: Схема данных (например, "lkapi")
          schema:
            type: string
            examples: ["lkapi"]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешный ответ с данными о текущих сервисах.
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      app:
                        type: string
                        examples: ["platex-rest-api"]
                      version:
                        type: string
                        examples: ["1.1.21"]
                      server_date:
                        type: string
                        format: date-time
                        examples: ["2025-03-25T08:26:44"]
                      status:
                        type: integer
                        examples: [200]
                      time_ms:
                        type: integer
                        examples: [188]
                      token:
                        type: object
                        properties:
                          token:
                            type: string
                            examples: ["2a9c8f36-e76b-43a2-a800-97d9f1869e0a"]
                      method:
                        type: string
                        examples: ["GET"]
                      path:
                        type: array
                        items:
                          type: string
                        examples: [["lkapi.current_service"]]
                      act:
                        type: string
                        examples: ["s"]
                      in:
                        type: array
                        items:
                          type: string
                        examples: [[]]
                      sql_info:
                        type: string
                        examples: ["4 queries, 0.154 sec"]
                      ref_table:
                        type: string
                        examples: ["lkapi.current_service"]
                      count:
                        type: integer
                        examples: [8]
                      total:
                        type: integer
                        examples: [8]
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CurrentService'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
      name: Authorization
  schemas:
    CurrentService:
      type: object
      properties:
        account_dn:
          type: ["string", "null"]
          nullable: true
          examples: ["94d28d19-1e62-4a4f-b46e-9bbc4a059152", null]
        account_dt:
          type: ["string", "null"]
          format: date-time
          nullable: true
          examples: ["2025-03-05T23:00:00+02", null]
        account_id:
          type: ["integer", "null"]
          nullable: true
          examples: [4, null]
        account_no:
          type: ["string", "null"]
          nullable: true
          examples: ["94d28d19-1e62-4a4f-b46e-9bbc4a059152", null]
        actual_account_dn:
          type: string
          examples: ["94d28d19-1e62-4a4f-b46e-9bbc4a059152"]
        actual_account_id:
          type: integer
          examples: [4]
        actual_begin_dt:
          type: string
          format: date-time
          examples: ["2025-03-05T23:00:00+02"]
        actual_end_dt:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        actual_is_archived:
          type: boolean
          examples: [false]
        actual_is_deleted:
          type: boolean
          examples: [false]
        actual_object_dn:
          type: string
          examples: ["ЦОД"]
        actual_object_id:
          type: integer
          examples: [2]
        actual_period:
          type: string
          examples: ["05.03.2025 23:00"]
        actual_service_kind_dn:
          type: string
          examples: ["Интернет"]
        actual_service_kind_id:
          type: integer
          examples: [2]
        addr_j:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        attr_j:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        begin_dt:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        bill_group_cd:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        bill_group_dn:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        bill_group_id:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        bill_group_nm:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        changed:
          type: string
          format: date-time
          examples: ["2025-03-06T17:44:47.459296+02"]
        changer:
          type: string
          examples: ["Tester:arav"]
        changer_id:
          type: integer
          examples: [21]
        chg:
          type: integer
          examples: [171676]
        clsf_j:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        contract_dn:
          type: string
          examples: ["Договор Тестовича от 05.03.2025"]
        contract_dt:
          type: string
          format: date-time
          examples: ["2025-03-05T23:00:00+02"]
        contract_id:
          type: integer
          examples: [16]
        contract_no:
          type: string
          examples: ["Договор Тестовича"]
        cost:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        cost_dn:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        created:
          type: string
          format: date-time
          examples: ["2025-03-06T17:44:47.459296+02"]
        creator:
          type: string
          examples: ["Tester:arav"]
        creator_id:
          type: integer
          examples: [21]
        curr_dn:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        curr_id:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        customer_dn:
          type: string
          examples: ["Test Testerovich"]
        customer_id:
          type: integer
          examples: [6]
        display_name:
          type: string
          examples: ["1 IP адрес"]
        end_dt:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        group_name:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        is_archived:
          type: boolean
          examples: [false]
        is_deleted:
          type: boolean
          examples: [false]
        is_once:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        name:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        note:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        object_cd:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        object_dn:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        object_id:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        object_nm:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        operator_cd:
          type: ["string", "null"]
          nullable: true
          examples: [null]
        operator_dn:
          type: string
          examples: ["Тестовый продавец"]
        operator_id:
          type: integer
          examples: [8]
        operator_nm:
          type: string
          examples: ["Тестовый продавец"]
        pack_cd:
          type: ["string", "null"]
          nullable: true
          examples: [null]
