openapi: 3.1.0
info:
  title: LKAPI Current Service API
  description: API для получения текущей информации о сервисах.
  version: "1.1.21"
servers:
  - url: https://apilk.iqdata.net
    description: Основной сервер для LKAPI
    variables:
      host:
        default: apilk.iqdata.net
paths:
  /index.php/lkapi.current_service:
    get:
      summary: Получить текущую информацию о сервисах
      description: Возвращает список текущих услуг для указанного аккаунта.
      operationId: getCurrentService
      parameters:
        - name: _debug
          in: query
          description: Флаг отладки (1 - включить, 0 - выключить)
          required: false
          schema:
            type: integer
            default: 0
        - name: _tz
          in: query
          description: Таймзона в минутах (например, 120 для GMT+2)
          required: false
          schema:
            type: integer
            default: 120
        - name: _schema
          in: query
          description: Схема данных (например, "lkapi")
          required: false
          schema:
            type: string
            default: lkapi
        - name: token
          in: header
          description: Токен для аутентификации пользователя
          required: true
          schema:
            type: string
        - name: db
          in: header
          description: Идентификатор базы данных
          required: true
          schema:
            type: string
            example: imaqliq_abonent
        - name: _app
          in: header
          description: Идентификатор версии приложения
          required: true
          schema:
            type: string
            example: platex_lk_application;1.1.10
        - name: Origin
          in: header
          description: Происхождение запроса
          required: true
          schema:
            type: string
            example: https://lk.iqdata.net
      responses:
        '200':
          description: Успешный ответ с данными о текущих сервисах.
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      app:
                        type: string
                        example: platex-rest-api
                      version:
                        type: string
                        example: 1.1.21
                      server_date:
                        type: string
                        format: date-time
                        example: "2025-03-25T09:07:25"
                      status:
                        type: integer
                        example: 200
                      time_ms:
                        type: integer
                        example: 113
                      token:
                        type: object
                        properties:
                          token:
                            type: string
                            example: 2ac5bd3c-aa9d-4cfa-810a-a63fd39ef984
                      method:
                        type: string
                        example: GET
                      path:
                        type: array
                        items:
                          type: string
                        example: [lkapi.current_service]
                      act:
                        type: string
                        example: s
                      in:
                        type: array
                        items:
                          type: string
                        example: []
                      sql_info:
                        type: string
                        example: "4 queries, 0.084 sec"
                      ref_table:
                        type: string
                        example: lkapi.current_service
                      count:
                        type: integer
                        example: 8
                      total:
                        type: integer
                        example: 8
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CurrentService'
        '400':
          description: Неверный запрос
        '401':
          description: Неавторизованный доступ
        '500':
          description: Внутренняя ошибка сервера
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CurrentService:
      type: object
      properties:
        account_dn:
          type: string
          nullable: true
          example: "94d28d19-1e62-4a4f-b46e-9bbc4a059152"
        account_dt:
          type: string
          format: date-time
          nullable: true
          example: "2025-03-05T23:00:00+02"
        account_id:
          type: integer
          nullable: true
          example:
