openapi: 3.0.3
info:
  title: Profile API
  version: 1.0.0
servers:
  - url: https://apilk.iqdata.net
paths:
  /index.php/lkapi.profile:
    get:
      summary: Получение профиля пользователя
      parameters:
        - name: _debug
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: _tz
          in: query
          required: false
          schema:
            type: integer
            default: 180
        - name: _schema
          in: query
          required: false
          schema:
            type: string
            default: lkapi
        - name: token
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  data:
                    type: object
              examples:
                success:
                  summary: Пример успешного ответа
                  value:
                    {
                      "status": "OK",
                      "data": {
                        "id": 123,
                        "name": "Иван Иванов",
                        "email": "ivan@example.com"
                      }
                    }
        "401":
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
                  message:
                    type: string
                    example: "Invalid or missing token"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"
                  message:
                    type: string
                    example: "Unexpected error occurred"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: token
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: "Иван Иванов"
        email:
          type: string
          example: "ivan@example.com"
security:
  - ApiKeyAuth: []
