openapi: 3.1.0
info:
  title: API Documentation for LKAPI
  description: API for accessing user profile information.
  version: 1.0.0
servers:
  - url: https://apilk.iqdata.net
    description: Main server for LKAPI
    variables:
      host:
        default: apilk.iqdata.net
paths:
  /index.php/lkapi.profile:
    get:
      summary: Get user profile data
      description: Retrieve profile information based on the given parameters.
      operationId: getProfile
      parameters:
        - name: _debug
          in: query
          description: Enable debug mode
          required: false
          schema:
            type: integer
            default: 1
        - name: _tz
          in: query
          description: Timezone offset in minutes
          required: false
          schema:
            type: integer
            default: 180
        - name: _schema
          in: query
          description: Schema identifier for the request
          required: false
          schema:
            type: string
            default: lkapi
        - name: token
          in: header
          description: Token for user authentication
          required: true
          schema:
            type: string
        - name: db
          in: header
          description: Database identifier
          required: true
          schema:
            type: string
            example: imaqliq_abonent
        - name: _app
          in: header
          description: Application version identifier
          required: true
          schema:
            type: string
            example: platex_lk_application;1.1.10
        - name: Origin
          in: header
          description: Origin of the request
          required: true
          schema:
            type: string
            example: https://lk.iqdata.net
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    description: Profile data
                    properties:
                      userId:
                        type: integer
                        example: 12345
                      username:
                        type: string
                        example: user_example
                      fullName:
                        type: string
                        example: John Doe
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

